import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildSchema, buildServices, loadSpec, loadOptionalSpec } from './lib/spec-model.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SOURCES = [
  { service: 'api', file: 'openapi/api.json' },
  { service: 'oauth2', file: 'openapi/oauth2.json' },
  { service: 'legacyAuth', file: 'openapi/auth.json' }
];

function renderModule(generated) {
  const payload = JSON.stringify(generated, null, 2);

  return [
    '// This file is auto-generated by scripts/generate-client.mjs',
    '// Do not edit manually.',
    '',
    `export const GENERATED = ${payload};`,
    'export const SERVICES = GENERATED.services;',
    "export const SERVICE_KEYS = Object.freeze(Object.keys(SERVICES));",
    ''
  ].join('\n');
}

function renderSchemaModule(schema) {
  return [
    '// This file is auto-generated by scripts/generate-client.mjs',
    '// Do not edit manually. Source: openapi/dbref.json',
    '',
    `export const SCHEMA = ${JSON.stringify(schema, null, 2)};`,
    'export const SCHEMA_RESOURCES = Object.freeze(Object.keys(SCHEMA));',
    ''
  ].join('\n');
}

async function main() {
  const specEntries = [];

  for (const source of SOURCES) {
    const doc = await loadSpec(path.join(ROOT, source.file));
    specEntries.push({ ...source, doc });
  }

  const generated = {
    // Deterministic by default (avoids per-build/test git churn). Publish
    // pipelines can stamp a real timestamp by setting ZEYOS_GENERATED_AT.
    generatedAt: process.env.ZEYOS_GENERATED_AT ?? null,
    services: buildServices(specEntries)
  };

  const outputFile = path.join(ROOT, 'src/generated/operations.js');
  await mkdir(path.dirname(outputFile), { recursive: true });
  await writeFile(outputFile, renderModule(generated), 'utf8');

  const dbref = await loadOptionalSpec(path.join(ROOT, 'openapi/dbref.json'));
  const schema = buildSchema(dbref);
  await writeFile(path.join(ROOT, 'src/generated/schema.js'), renderSchemaModule(schema), 'utf8');

  const operationCount = Object.values(generated.services)
    .map((service) => service.operations.length)
    .reduce((sum, value) => sum + value, 0);

  process.stdout.write(`Generated operations for ${Object.keys(generated.services).length} services (${operationCount} operations).\n`);
  process.stdout.write(`Generated schema for ${Object.keys(schema).length} resources.\n`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
